services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  mariadb:

networks:
  inception: